# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with the necessary version
FROM node:20-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json .

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js image for production
FROM node:20-alpine AS production

# Set the working directory
WORKDIR /app

# Copy only the build files from the builder stage
COPY --from=builder /app/build /app/build

# Copy package.json and install production dependencies only
COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm ci --omit=dev

# Expose the port that the app runs on
EXPOSE 3000

# Start the application
CMD ["node", "build/index.js"]